name: Oraxen
main: io.th0rgal.oraxen.OraxenPlugin
version: 1.192.1
api-version: "1.20"
author: Th0rgal
description: Powerful resource-pack item & block system
website: https://oraxen.com
load: POSTWORLD
depend: [ProtocolLib]
softdepend: []
commands:
  oraxen:
    description: Main command
    usage: /oraxen
