name: Build on push

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew core:build

      - name: Build with Gradle
        run: ./gradlew core:build

      # 把构建产物保存为 Actions Artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-build          # 下载时看到的文件名
          path: core/build/libs     # 真正要打包的目录或文件
