on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 清理并构建完整可运行 jar（包含所有依赖）
      - name: Build fat-jar with shadowJar
        run: |
          ./gradlew clean shadowJar --no-daemon --stacktrace

      # 5. 上传最终的 fat-jar（路径按你项目实际输出目录写）
      - name: Upload fat-jar
        uses: actions/upload-artifact@v4
        with:
          name: oraxen-fat-jar
          path: core/build/libs/*-all.jar   # shadowJar 默认命名带 -all

