name: Build on push

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build   # 改成这样

      # 可选：把构建产物当 Actions Artifact 下载
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oraxen-build
          path: |
            core/build/libs/*.jar
            */build/libs/*.jar

